export const CREATE = 'create'
export const UPDATE = 'update'
export const DELETE = 'delete'
export const FETCHLIST = 'fetchList'
export const COMPLETED = 'completed'
export const UNCOMPLETED = 'uncompleted'
export const UPDATETASK = 'updateTask'